project: ReBRAC
program: src/algorithms/rebrac.py
method: grid
parameters:
  config_path:
    values: [
    "configs/rebrac/door/door_cloned.yaml",
    "configs/rebrac/door/door_human.yaml",
    "configs/rebrac/door/door_expert.yaml",

    "configs/rebrac/hammer/hammer_cloned.yaml",
    "configs/rebrac/hammer/hammer_human.yaml",
    "configs/rebrac/hammer/hammer_expert.yaml",

    "configs/rebrac/pen/pen_cloned.yaml",
    "configs/rebrac/pen/pen_human.yaml",
    "configs/rebrac/pen/pen_expert.yaml",

    "configs/rebrac/relocate/relocate_cloned.yaml",
    "configs/rebrac/relocate/relocate_human.yaml",
    "configs/rebrac/relocate/relocate_expert.yaml",
    ]
  train_seed:
     values: [0, 1, 2, 3]
  actor_bc_coef:
    values: [0.001, 0.01, 0.05, 0.1]
  critic_bc_coef:
     values: [0, 0.001, 0.01, 0.1, 0.5]
