project: ReBRAC
program: src/algorithms/rebrac.py
method: grid
parameters:
  config_path:
    values: [
     "configs/td3_bc/antmaze/antmaze_umaze_diverse.yaml",
     "configs/td3_bc/antmaze/antmaze_medium_diverse.yaml",
     "configs/td3_bc/antmaze/antmaze_large_diverse.yaml",

     "configs/td3_bc/antmaze/antmaze_umaze.yaml",
     "configs/td3_bc/antmaze/antmaze_medium_play.yaml",
     "configs/td3_bc/antmaze/antmaze_large_play.yaml",
    ]
  train_seed:
     values: [0, 1, 2, 3]
  actor_bc_coef:
     values: [0.0005, 0.001, 0.002, 0.003, 0.4]
