project: ReBRAC
program: src/algorithms/rebrac.py
method: grid
parameters:
  config_path:
    values: [
      "configs/rebrac/halfcheetah/halfcheetah_medium.yaml",
      "configs/rebrac/halfcheetah/halfcheetah_medium_expert.yaml",
      "configs/rebrac/halfcheetah/halfcheetah_medium_replay.yaml",

      "configs/rebrac/halfcheetah/halfcheetah_random.yaml",
      "configs/rebrac/halfcheetah/halfcheetah_expert.yaml",
      "configs/rebrac/halfcheetah/halfcheetah_full_replay.yaml",

      "configs/rebrac/walker2d/walker2d_medium.yaml",
      "configs/rebrac/walker2d/walker2d_medium_expert.yaml",
      "configs/rebrac/walker2d/walker2d_medium_replay.yaml",

      "configs/rebrac/walker2d/walker2d_random.yaml",
      "configs/rebrac/walker2d/walker2d_expert.yaml",
      "configs/rebrac/walker2d/walker2d_full_replay.yaml",

      "configs/rebrac/hopper/hopper_medium.yaml",
      "configs/rebrac/hopper/hopper_medium_expert.yaml",
      "configs/rebrac/hopper/hopper_medium_replay.yaml",

      "configs/rebrac/hopper/hopper_random.yaml",
      "configs/rebrac/hopper/hopper_expert.yaml",
      "configs/rebrac/hopper/hopper_full_replay.yaml",
    ]
  train_seed:
     values: [10, 11, 12, 13]
  batch_size:
    value: 256
  actor_learning_rate:
    value: 0.0003
  critic_learning_rate:
    value: 0.0003
