actor_bc_coef: 0.1
actor_learning_rate: 0.0003
batch_size: 256
buffer_size: 1000000
checkpoints_path: null
critic_bc_coef: 0.1
critic_learning_rate: 0.0003
critic_ln: true
dataset_name: medium
device: cuda
discount: 0.99
encoder_learning_rate: 0.0003
eval_freq: 1000
eval_seed: 0
expl_noise: 0.1
group: ReBRAC-cheetah_run-medium
hidden_dim: 256
load_model: ''
max_timesteps: 300000
n_episodes: 10
name: ReBRAC
noise_clip: 0.5
normalize: false
normalize_reward: false
policy_freq: 2
policy_noise: 0.2
project: ReBRAC
seed: 0
task_name: cheetah_run
tau: 0.005
