project: ReBRAC
program: src/algorithms/rebrac_torch_vis.py
method: grid
parameters:
  config_path:
    values: [
    "configs/rebrac-vis/walker_walk/expert.yaml",
    "configs/rebrac-vis/walker_walk/medium_expert.yaml",
    "configs/rebrac-vis/walker_walk/medium.yaml",
    "configs/rebrac-vis/walker_walk/medium_replay.yaml",
    "configs/rebrac-vis/walker_walk/random.yaml",

    "configs/rebrac-vis/cheetah_run/expert.yaml",
    "configs/rebrac-vis/cheetah_run/medium_expert.yaml",
    "configs/rebrac-vis/cheetah_run/medium.yaml",
    "configs/rebrac-vis/cheetah_run/medium_replay.yaml",
    "configs/rebrac-vis/cheetah_run/random.yaml",

    "configs/rebrac-vis/humanoid_walk/expert.yaml",
    "configs/rebrac-vis/humanoid_walk/medium_expert.yaml",
    "configs/rebrac-vis/humanoid_walk/medium.yaml",
    "configs/rebrac-vis/humanoid_walk/medium_replay.yaml",
    "configs/rebrac-vis/humanoid_walk/random.yaml",

    ]
  seed:
     values: [10, 11, 12, 13, 14]
